### ISSUE TITLE
[ENHANCEMENT] Refactoring JS code

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#43]
### Description

To assure code quality and a good DX (Developer Experience), the JavaScript code has to be refactored

### Acceptance Criteria

- [ ] no console.log
- [ ] no DRY
- [ ] each function should stand on its own
- [ ] deletion of unused code

💡 **Note:** comments should stay for learning purpose!

```[tasklist]
### Tasks
- [ ] check of `let` and `const` usage
```

**Comment by traez** [comment]
I love your simple, minimalistic yet very key website for beginners/gaming.
Would love to contribute sometime if possible, as I've just kick-started my Open Source career.

**Comment by YuriDevAT** [comment]
Hi @traez welcome to the Open Source community. This particular repo is mostly updated by staff themselves. Also, YurisCodingClub is focusing on collaborating with women and people with disabilities. Hopefully, you find a community that fits your needs better (check out [EddieHub](eddiejaoude.github.io/) e.g., great way to start your Open Source Career 😉)
